[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "Artificial Intelligence and Energy: Investigating the Applications and Economic Implications of Intelligent Technologies in the Energy Industry"
